name: Check
on: [ pull_request, push ]
jobs:
  check:
    runs-on: ubuntu-latest
    # push: always run.
    # pull_request: run only when the PR is submitted from a forked repository, not within this repository.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        aware-config: [ "aware-config-mysql.json", "aware-config-postgres.json" ]
    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        ports:
        - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: tester
          MYSQL_PASSWORD: password
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: tester
          POSTGRES_DB: test_database
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up OpenJDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: "temurin"
        cache: "gradle"
    - name: Connect to MySQL
      run: mysql -h 127.0.0.1 --port 3306 -uroot -proot -e "show databases;"
    - name: Create a test database on MySQL
      run: mysql -h 127.0.0.1 --port 3306 -uroot -proot -e "create database test_database;"
    - name: Grant on a test database to a test user on MySQL
      run: mysql -h 127.0.0.1 --port 3306 -uroot -proot -e "grant all privileges on test_database.* to 'tester';"
    - name: Show tables on MySQL
      run: mysql -h 127.0.0.1 --port 3306 -utester -ppassword -Dtest_database -e "show tables;"
    - name: Connect to PostgreSQL
      run: psql -h localhost -p 5432 -U tester -d test_database -c "\l"
      env:
        PGPASSWORD: "password"
    - name: Check
      run: ./gradlew --stacktrace check
      env:
        AWARE_TEST_CONFIG_PATH: ${{ matrix.aware-config }}
    - name: Show tables on MySQL
      run: mysql -h 127.0.0.1 --port 3306 -utester -ppassword -Dtest_database -e "show tables;"
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: build/reports/tests/test
