name: Check
on: [ pull_request, push ]
jobs:
  check_mysql:
    runs-on: ubuntu-latest
    # push: always run.
    # pull_request: run only when the PR is submitted from a forked repository, not within this repository.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        ports:
        - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up OpenJDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: "temurin"
        cache: "gradle"
    - name: Connect to MySQL
      run: mysql -h 127.0.0.1 --port 3306 -uroot -proot -e "show databases;"
    - name: Create a test database on MySQL
      run: mysql -h 127.0.0.1 --port 3306 -uroot -proot -e "create database test_db;"
    - name: Grant on a test database to a test user on MySQL
      run: mysql -h 127.0.0.1 --port 3306 -uroot -proot -e "grant all privileges on test_db.* to 'user';"
    - name: Grant on a test database to a test user on MySQL
      run: mysql -h 127.0.0.1 --port 3306 -uuser -ppassword -Dtest_db -e "show tables;"
    - name: Check
      run: ./gradlew --stacktrace check
